t = ('lahore','karachi', 'sindh', 'hyderabad','islamabad','pindi')
temp = list(t)
temp.append('quetta')
t = tuple(temp)
print(t)
temp.sort()
t = tuple(temp)
print(t)
temp.reverse()
t = tuple(temp)
print(t)